CREATE TABLE comment
(
	commentNo INT AUTO_INCREMENT PRIMARY KEY,
	no INT NOT NULL,
	name VARCHAR(20) NOT NULL,
	comment TEXT NOT NULL,
	wTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	commentCnt INT NOT NULL DEFAULT 0
);